**MK Rekayasa Fitur**

**Topik:** Ekstraksi Fitur

* **Teknik Manual - Data Terstruktur**

**Galih Hermawan. Prodi Teknik Informatika. UNIKOM**

---

In [1]:
import pandas as pd
import numpy as np

# Data yang direvisi
data = {
    'kode_transaksi': ['TRX001', 'TRX001', 'TRX001', 'TRX002', 'TRX003', 'TRX004', 'TRX005', 'TRX001', None],
    'tanggal_transaksi': ['2024-05-01', '2024-05-01', '2024-05-01', '2024-05-03', '2024-05-03', '2024-05-04', '2024-06-01', '2024-05-01', None],
    'id_barang': [101, 104, 105, 102, 103, 104, 105, 105, 101],
    'nama_barang': ['Buku Tulis', 'Penghapus', 'Gunting', 'Pensil', 'Lem', 'Penghapus', 'Gunting', 'Gunting', 'Buku Tulis'],
    'kategori': ['Alat Tulis', 'Alat Tulis', 'Perangkat', 'Alat Tulis', 'Perangkat', 'Alat Tulis', 'Perangkat', 'Perangkat', 'Alat Tulis'],
    'harga_satuan': [5000, 1500, 3000, 1000, 2000, 1500, 3000, 3000, 5000],
    'jumlah': [20, 30, 2, 15, 10, 10, 5, 2, 2]
}

# Membuat DataFrame
df = pd.DataFrame(data)

# Menampilkan DataFrame
print("Data penjualan awal:")
df

Data penjualan awal:

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah
0,TRX001,2024-05-01,101,Buku Tulis,Alat Tulis,5000,20
1,TRX001,2024-05-01,104,Penghapus,Alat Tulis,1500,30
2,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2
3,TRX002,2024-05-03,102,Pensil,Alat Tulis,1000,15
4,TRX003,2024-05-03,103,Lem,Perangkat,2000,10
5,TRX004,2024-05-04,104,Penghapus,Alat Tulis,1500,10
6,TRX005,2024-06-01,105,Gunting,Perangkat,3000,5
7,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2
8,None,None,101,Buku Tulis,Alat Tulis,5000,2

In [2]:
# Menampilkan baris DataFrame yang memiliki setidaknya satu nilai kosong
baris_kosong = df[df.isna().any(axis=1)]
print("Baris dengan setidaknya satu nilai kosong:")
baris_kosong

Baris dengan setidaknya satu nilai kosong:

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah
8,None,None,101,Buku Tulis,Alat Tulis,5000,2

In [3]:
# Menghapus baris yang memiliki setidaknya satu nilai kosong
data_tidak_kosong = df.dropna()

# Menampilkan DataFrame yang telah dibersihkan
print("DataFrame setelah menghapus data kosong:")
data_tidak_kosong

DataFrame setelah menghapus data kosong:

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah
0,TRX001,2024-05-01,101,Buku Tulis,Alat Tulis,5000,20
1,TRX001,2024-05-01,104,Penghapus,Alat Tulis,1500,30
2,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2
3,TRX002,2024-05-03,102,Pensil,Alat Tulis,1000,15
4,TRX003,2024-05-03,103,Lem,Perangkat,2000,10
5,TRX004,2024-05-04,104,Penghapus,Alat Tulis,1500,10
6,TRX005,2024-06-01,105,Gunting,Perangkat,3000,5
7,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2

In [4]:
# Mendeteksi adanya data duplikat
data_duplikat = data_tidak_kosong[data_tidak_kosong.duplicated()]

# Menampilkan baris DataFrame yang merupakan duplikat
print("Baris DataFrame yang merupakan duplikat:")
data_duplikat

Baris DataFrame yang merupakan duplikat:

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah
7,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2

In [5]:
# Menghapus data duplikat dan mempertahankan satu baris duplikat saja
data_bersih = data_tidak_kosong.drop_duplicates()

# Menampilkan DataFrame setelah menghapus data duplikat
print("DataFrame setelah menghapus data duplikat:")
data_bersih

DataFrame setelah menghapus data duplikat:

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah
0,TRX001,2024-05-01,101,Buku Tulis,Alat Tulis,5000,20
1,TRX001,2024-05-01,104,Penghapus,Alat Tulis,1500,30
2,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2
3,TRX002,2024-05-03,102,Pensil,Alat Tulis,1000,15
4,TRX003,2024-05-03,103,Lem,Perangkat,2000,10
5,TRX004,2024-05-04,104,Penghapus,Alat Tulis,1500,10
6,TRX005,2024-06-01,105,Gunting,Perangkat,3000,5

In [6]:
# Menambah kolom baru "harga_subtotal"
df_baru = data_bersih.copy()
df_baru['harga_subtotal'] = df_baru['harga_satuan'] * df_baru['jumlah']

# Menampilkan DataFrame setelah penambahan kolom baru
df_baru

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah,harga_subtotal
0,TRX001,2024-05-01,101,Buku Tulis,Alat Tulis,5000,20,100000
1,TRX001,2024-05-01,104,Penghapus,Alat Tulis,1500,30,45000
2,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2,6000
3,TRX002,2024-05-03,102,Pensil,Alat Tulis,1000,15,15000
4,TRX003,2024-05-03,103,Lem,Perangkat,2000,10,20000
5,TRX004,2024-05-04,104,Penghapus,Alat Tulis,1500,10,15000
6,TRX005,2024-06-01,105,Gunting,Perangkat,3000,5,15000

In [7]:
# Mengelompokkan DataFrame berdasarkan kode_transaksi dan menjumlahkan subtotal
total_harga_per_transaksi = df_baru.groupby('kode_transaksi')['harga_subtotal'].sum()
total_harga_per_transaksi

kode_transaksi
TRX001    151000
TRX002     15000
TRX003     20000
TRX004     15000
TRX005     15000
Name: harga_subtotal, dtype: int64

In [8]:
# Mengelompokkan DataFrame berdasarkan kode_transaksi dan menjumlahkan subtotal
total_harga_per_transaksi2 = df_baru.groupby('kode_transaksi')['harga_subtotal'].sum().reset_index()

# Mengubah nama kolom menjadi "total"
total_harga_per_transaksi2 = total_harga_per_transaksi2.rename(columns={'harga_subtotal': 'total'})

# Menggabungkan total harga per transaksi dengan DataFrame asli
df_merged = pd.merge(df_baru, total_harga_per_transaksi2, on='kode_transaksi')

df_merged

,kode_transaksi,tanggal_transaksi,id_barang,nama_barang,kategori,harga_satuan,jumlah,harga_subtotal,total
0,TRX001,2024-05-01,101,Buku Tulis,Alat Tulis,5000,20,100000,151000
1,TRX001,2024-05-01,104,Penghapus,Alat Tulis,1500,30,45000,151000
2,TRX001,2024-05-01,105,Gunting,Perangkat,3000,2,6000,151000
3,TRX002,2024-05-03,102,Pensil,Alat Tulis,1000,15,15000,15000
4,TRX003,2024-05-03,103,Lem,Perangkat,2000,10,20000,20000
5,TRX004,2024-05-04,104,Penghapus,Alat Tulis,1500,10,15000,15000
6,TRX005,2024-06-01,105,Gunting,Perangkat,3000,5,15000,15000

In [9]:
# Kelompokkan DataFrame berdasarkan "kode_transaksi" dan "tanggal_transaksi", lalu hitung total
df_total = df_baru.groupby('kode_transaksi')['harga_subtotal'].sum().reset_index()

# Ubah nama kolom "harga_subtotal" yang menampung penjumlahan menjadi "total"
df_total.rename(columns={'harga_subtotal': 'total'}, inplace=True)

# Gabungkan dengan DataFrame asli untuk mendapatkan tanggal_transaksi
df_total = pd.merge(df_total, df_baru[['kode_transaksi', 'tanggal_transaksi']].drop_duplicates(), on='kode_transaksi')


# Menampilkan DataFrame baru yang hanya berisi "kode_transaksi", "tanggal", dan "total"
df_total[['kode_transaksi', 'tanggal_transaksi', 'total']]

  kode_transaksi tanggal_transaksi   total
0         TRX001        2024-05-01  151000
1         TRX002        2024-05-03   15000
2         TRX003        2024-05-03   20000
3         TRX004        2024-05-04   15000
4         TRX005        2024-06-01   15000

In [10]:
# Hitung total transaksi di setiap tanggal
total_per_tanggal = df_total.groupby('tanggal_transaksi')['total'].sum().reset_index()

total_per_tanggal

  tanggal_transaksi   total
0        2024-05-01  151000
1        2024-05-03   35000
2        2024-05-04   15000
3        2024-06-01   15000

In [11]:
# Ubah tanggal_transaksi menjadi objek datetime
df_total['tanggal_transaksi'] = pd.to_datetime(df_total['tanggal_transaksi'])

# Ekstraksi bulan dan tahun dari tanggal_transaksi
df_total['bulan'] = df_total['tanggal_transaksi'].dt.month
df_total['tahun'] = df_total['tanggal_transaksi'].dt.year

# Hitung total transaksi di setiap bulan
total_per_bulan = df_total.groupby(['tahun', 'bulan'])['total'].sum().reset_index()

total_per_bulan

   tahun  bulan   total
0   2024      5  201000
1   2024      6   15000

<hr>
Beberapa contoh ekstraksi fitur yang dapat dilakukan berdasarkan DataFrame sebelumnya:

1. **Menghitung Total Belanja Setiap Pelanggan**: Jika Anda memiliki informasi tentang pelanggan, Anda dapat menghitung total belanja mereka dengan mengelompokkan transaksi berdasarkan kode pelanggan (misalnya, menggunakan kolom kode_transaksi) dan kemudian menjumlahkan total belanja mereka.
   
2. **Ekstraksi Bulan dan Tahun dari Tanggal Transaksi**: Dari kolom tanggal_transaksi, Anda dapat mengekstraksi informasi bulan dan tahun untuk setiap transaksi. Ini dapat membantu dalam menganalisis tren belanja atau pola musiman.

3. **Menghitung Rata-rata Harga Satuan**: Anda dapat menghitung rata-rata harga satuan barang yang dibeli dari seluruh transaksi. Ini dapat memberikan pemahaman tentang harga rata-rata barang yang dijual.

4. **Membuat Fitur Baru Berdasarkan Kategori Barang**: Anda dapat membuat fitur biner untuk masing-masing kategori barang yang ada, misalnya, kolom 'is_alat_tulis', 'is_perangkat', dan seterusnya, di mana nilai 1 menunjukkan keberadaan barang dalam kategori tersebut dalam transaksi, dan 0 sebaliknya.

5. **Menghitung Total Jumlah Barang yang Dibeli**: Anda dapat menghitung total jumlah barang yang dibeli dalam setiap transaksi. Ini dapat memberikan informasi tentang ukuran transaksi.

6. **Menghitung Jumlah Jenis Barang yang Dibeli**: Anda dapat menghitung jumlah jenis barang yang dibeli dalam setiap transaksi. Ini dapat memberikan informasi tentang keragaman pembelian pelanggan.

7. **Menghitung Frekuensi Belanja Setiap Pelanggan**: Jika Anda memiliki informasi tentang pelanggan, Anda dapat menghitung frekuensi belanja mereka dengan menghitung jumlah transaksi yang dilakukan oleh setiap pelanggan.

8. **Menghitung Total Harga per Barang**: Anda dapat menghitung total harga per barang dengan mengalikan harga satuan dengan jumlah barang untuk setiap transaksi.

Dengan menggabungkan data mentah dengan fitur-fitur yang diekstraksi seperti ini, Anda dapat mempersiapkan dataset yang lebih lengkap dan informatif untuk analisis lebih lanjut atau pemodelan.